nav/urls.py
from django.urls import path
from . import views



app_name = 'nav'

urlpatterns = [
    # ~~~~~~~~~~~~~~~~~ page ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('page/sites/', views.page_site_list, name='page-sites'),

    # ~~~~~~~~~~~~~~~~~ api ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('api/sites/', views.api_site_list, name='api-sites'),
    path('api/add_user_site/', views.api_add_user_site, name='api-add-user-site'),
    path('api/remove_user-site/', views.api_remove_user_site, name='api-remove-user-site'),
]

nav/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import ImageField, CharField, URLField, IntegerField, BooleanField


class Site(models.Model):
    DATAS = 'DATAS'
    NEWS = 'NEWS'
    OTHERS = 'OTHERS'
    PERSONAL = 'PERSONAL'
    CATEGORY_CHOICES = (
        (DATAS,'数据'),
        (NEWS, '新闻'),
        (OTHERS,'其他'),
        (PERSONAL, '用户自定义'),
    )
    name = CharField(max_length=20, blank=False, default='')
    url = URLField(blank=False, default='')
    icon = ImageField(blank=True, upload_to='icons/')
    description = CharField(max_length=100, blank=True)
    category = CharField(max_length=10, choices=CATEGORY_CHOICES, default=OTHERS)
    order = IntegerField(default=100)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sites', blank=True, null=True, default=None)

nav/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.views.decorators.csrf import ensure_csrf_cookie
from rest_framework.decorators import api_view, renderer_classes, throttle_classes
from rest_framework.exceptions import NotAuthenticated, APIException
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from a_stock.exceptions import OperateError
from a_stock.throttles import UnsafeMethodThrottle
from a_stock.utils import print_err
from .models import Site
from .serializers import SiteSerializer


# ~~~~~~~~~~~~~~~~~~~ page ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

@api_view(('GET',))
@renderer_classes((TemplateHTMLRenderer,))
def page_site_list(request):
    return Response(template_name='nav/sites.html')


# ~~~~~~~~~~~~~~~~~~~ api ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@api_view(('GET',))
def api_site_list(request):
    q = (Q(owner=None) | Q(owner=request.user)) if request.user.is_authenticated else Q(owner=None)
    sites = Site.objects.filter(q).order_by('order')
    serializer = SiteSerializer(sites, many=True)
    return Response(serializer.data)


@api_view(('POST',))
@throttle_classes((UnsafeMethodThrottle,))
@ensure_csrf_cookie
def api_add_user_site(request):
    if not request.user.is_authenticated:
        raise NotAuthenticated(detail='请先登录')

    try:
        if Site.objects.filter(owner=request.user).count() > 1000:
            raise OperateError('用户自定义网址数量已达上限')

        ser = SiteSerializer(data=dict(name=request.data['name'], url=request.data['url'],
                                       category=Site.PERSONAL, owner=request.user.id))
        if ser.is_valid():
            ser.save()
            return Response(data=ser.data)
        raise OperateError(detail='参数错误，请检查。注意网址的格式是否正确。')
    except KeyError:
        raise OperateError(detail='参数错误，请检查')
    except APIException as e:
        raise e
    except Exception as e:
        print_err(e)
        raise APIException(detail='服务器出错')


@api_view(('POST',))
@throttle_classes((UnsafeMethodThrottle,))
@ensure_csrf_cookie
def api_remove_user_site(request):
    if not request.user.is_authenticated:
        raise NotAuthenticated(detail='请先登录')
    try:
        site = Site.objects.get(id=request.data['id'], owner=request.user)
        site.delete()
        return Response(dict(success=True, detail='操作成功，已删除'))
    except KeyError:
        raise OperateError(detail='参数错误，请检查')
    except ObjectDoesNotExist:
        raise OperateError(detail='操作失败，id或用户信息错误')
    except Exception as e:
        print_err(e)
        raise APIException(detail='服务器出错')

nav/templates/nav/sites.html
{% extends 'common/base.html' %}
{% load static %}
{% block subtitle %}导航{% endblock %}

{% block style %}
    <style>
        main {
            padding-top: 2.4rem;
        }

        .ic {
            width: 26px;
            height: 26px;
            padding: 4px;
        }

        div.container-fluid {
            padding-top: 2rem;
        }

        .site-container {
            padding: 1rem;
        }

    </style>
{% endblock %}

{% block content %}

    <div class="container-fluid text-white text-left bg-dark">

        <div class="container-fluid" style="padding-top: 0rem;">
            <div class="row"><h6 class="col-12">自定义</h6></div>
            <div class="row site-container" id="div-personal"></div>
            <div class="row" style="margin-left: 1rem">
                <form id="form-add-user-site" action="{% url 'nav:api-add-user-site' %}" method="post">
                    {% csrf_token %}
                    <div class="input-group input-group-sm mb-3">
                        <input id="input-site-name" name="name" type="text" class="form-control" placeholder="名称">
                        <input id="input-site-url" name="url" type="text" class="form-control"
                               placeholder="网址">
                        <div class="input-group-append">
                            <button id="btn-add-site" class="btn btn-primary" type="submit">
                                添加
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

        <div class="container-fluid">
            <div class="row"><h6 class="col-12">数据</h6></div>
            <div class="row  site-container" id="div-datas"></div>
        </div>

        <div class="container-fluid">
            <div class="row"><h6 class="col-12">新闻</h6></div>
            <div class="row site-container" id="div-news"></div>
        </div>

        <div class="container-fluid">
            <div class="row"><h6 class="col-12">其他</h6></div>
            <div class="row site-container" id="div-others"></div>
        </div>

    </div>

{% endblock %}

{% block script %}
    <script>
        'use strict';

        let get_sites = function () {
            $.ajax({
                url: "{% url 'nav:api-sites' %}",
                type: "GET",
                dataType: "json",
            }).done(function (sites) {
                parse_sites(sites);
            }).fail(function () {
            }).always(function () {
            });
        };


        let get_site_contaner = function (category) {
            let category_contaners = {
                'DATAS': $('#div-datas'),
                'NEWS': $('#div-news'),
                'OTHERS': $('#div-others'),
                'PERSONAL': $('#div-personal'),
            };
            return category_contaners[category];
        };


        let add_site = function (container, name, url, icon, id) {
            let ic = icon || "{% static 'common/img/default_favico.ico' %}";
            let img = $('<img></img>')
                .attr('src', ic)
                .addClass('align-bottom')
                .addClass('ic')
                .attr('data-id', id);
            let a = $('<a></a>')
                .attr('href', url)
                .attr('target', '_blank')
                .text(' ' + name)
                .addClass('align-bottom')
                .addClass('text-link');
            let col = $('<div></div>')
                .addClass('col-md-2')
                .prepend(img)
                .append(a);
            container.append(col)
        };

        let parse_sites = function (sites) {
            if (sites && sites.length > 0) {

                $.each(sites, function (i, v) {
                    try {
                        add_site(get_site_contaner(v.category), v.name, v.url, v.icon, v.id);
                    } catch (e) {
                        console.log(e);
                    }
                });
            }
        };

        let init_bg = function () {
            $('body').removeClass('bg-secondary').addClass('bg-dark');
        };

        let init_add_user_site = function () {
            $('#form-add-user-site').on('submit', function (e) {
                e.preventDefault();
                let name = $('#input-site-name').val();
                let url = $('#input-site-url').val();
                if (!name || !url) {
                    $.dialog('请填写名称和网址');
                    return;
                }
                if (!url.startsWith('http://') && !url.startsWith('https://')) {
                    $('#input-site-url').val('http://' + url);
                }
                let form = $(this);
                $.ajax({
                    url: form.attr('action'),
                    type: "POST",
                    data: form.serialize(),
                    dataType: "json",
                }).done(function (site) {
                    if (site && site.name && site.url) {
                        add_site(get_site_contaner('PERSONAL'), site.name, site.url, null ,site.id);
                        $('#input-site-name').val('');
                        $('#input-site-url').val('');
                        let d = $.dialog('添加成功！点击名称前的星星图标可删除。');
                        setTimeout(function(){
                            d.close();
                        }, 1400);
                    }
                }).fail(function (xhr, status, errorThrown) {
                }).always(function (xhr, status) {
                });
            });
        };

        let init_remove_user_site = function(){
            $('#div-personal').on('click', 'div img', function (e) {
                e.preventDefault();
                let id = $(this).attr('data-id');
                let site_ele = $(this).parent();
                $.confirm({
                    title: '提示',
                    content: '确认要删除？',
                    buttons: {
                        ok: {
                            text: '确认',
                            btnClass: 'btn-primary',
                            action: function(){
                                remove_user_site(id, function(){
                                    site_ele.remove();
                                });
                            }
                        },
                        cancel:{
                            text: '取消',
                        }
                    }
                });

            });
        };

        let remove_user_site = function(id, cb){
            $.ajax({
                    url: "{% url 'nav:api-remove-user-site' %}",
                    data: {'id':id},
                    type: "POST",
                    dataType:"json",
                }).done(function(r){
                    if(r.success && cb){
                        cb();
                    }
                });
        };


        $(function () {
            init_bg();
            active_nav_sites();
            get_sites();
            init_add_user_site();
            init_remove_user_site();
        });
    </script>
{% endblock %}