nav/urls.py
from django.urls import path
from . import views



app_name = 'nav'

urlpatterns = [
    # ~~~~~~~~~~~~~~~~~ page ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('page/sites/', views.page_site_list, name='page-sites'),

    # ~~~~~~~~~~~~~~~~~ api ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('api/sites/', views.api_site_list, name='api-sites'),
    path('api/add_user_site/', views.api_add_user_site, name='api-add-user-site'),
    path('api/remove_user-site/', views.api_remove_user_site, name='api-remove-user-site'),
]

stock_analyze/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'stock_analyze'

CACHE_TIME_LONG = 60 * 24
CACHE_TIME_MEDIUM = 60 * 10
CACHE_TIME_SHORT = 60 * 1

urlpatterns = [
    # ~~~~~~~~~~~~~~~~~~~~~ page html~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ex: /stock_analyze/page/index
    path('page/index/', views.page_index,
         name='page-index'),
    path('page/industry_list/', views.page_industries,
         name='page-industries'),
    path('page/industries/<int:id>/', views.page_industry_detail,
         name='page-industry-detail'),
    path('page/stocks/<int:id>/', views.page_stock_detail,
         name='page-stock-detail'),
    path('page/index_detail/<stock_code>/<market_code>/', views.page_index_detail,
         name='page-index-detail'),
    path('page/stocks/rzrq/<int:id>', views.page_stock_rzrq, name='page-stock-rzrq'),

    # ~~~~~~~~~~~~~~~~~~~~~~ api json ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ex: /stock_analyze/api/industries
    path('api/industries/', cache_page(CACHE_TIME_LONG)(views.IndustryList.as_view()),
         name='api-industry-list'),
    path('api/industries/<int:pk>/', cache_page(CACHE_TIME_LONG)(views.IndustryDetail.as_view()),
         name='api-industry-detail'),
    path('api/industries/stocks_updown/', cache_page(CACHE_TIME_SHORT)(views.all_industry_stocks_updown),
         name='api-all-stocks-updown'),
    path('api/industries/stocks_updown/<int:industry_id>/', cache_page(CACHE_TIME_SHORT)(views.industry_stocks_updown),
         name='api-stocks-updown'),
    path('api/stocks/<int:pk>/', cache_page(CACHE_TIME_SHORT)(views.StockDetail.as_view()),
         name='api-stock-detail'),
    path('api/stocks/cur_price_realtime/<stock_code>/<market_code>/', views.stock_cur_price_realtime,
         name='api-stock-cur-price-realtime'),
    path('api/stocks/cur_price/', cache_page(CACHE_TIME_SHORT)(views.stock_cur_price),
         name='api-stock-cur-price'),
    path('api/stocks/search/', views.stocks_search, name='api-stocks-search'),
    path('api/stocks/beta/<int:id>', cache_page(CACHE_TIME_LONG)(views.stock_beta), name='api-stocks-beta'),
    path('api/stocks/last_deal_data/<int:id>/', cache_page(CACHE_TIME_SHORT)(views.stock_last_deal_data),
         name='last_deal_data'),

    # ~~~~~~~~~~~~~~~~~~~~~~~~ api html ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('api/industries/stocks_corr_analyzation/<int:industry_id>', cache_page(CACHE_TIME_LONG)(views.industry_stocks_corr_analyzation),
         name='industry_stocks_corr_analyzation'),
    path('api/stocks/recent_data/<int:stock_id>/<int:days>', cache_page(CACHE_TIME_LONG)(views.stock_recent_data),
         name='stock_recent_data'),
    path('api/stocks/stock_pv_analyzation/<int:stock_id>', cache_page(CACHE_TIME_LONG)(views.stock_pv_analyzation),
         name='stock_pv_analyzation'),
    path('api/stocks/stocks_corr_analyzation/<int:stock_id>', cache_page(CACHE_TIME_LONG)(views.stocks_corr_analyzation),
         name='stocks_corr_analyzation'),

    # ~~~~~~~~~~~~~~~~~~~~~~~~~ api file ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('api/data_download/stocks/<int:stock_id>/<int:days>', views.download_stock_data,
         name='api-download-stock-data'),

]

stock_analyze/models.py
from django.db import models
from django.urls import reverse

import stock_analyze.helper.stock_data_analyzer as sda
import stock_analyze.helper.stock_data_manager as sdm

# ~~~~~~~~~~~~~~~~~~~~~ Stock ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
from stock_analyze.exceptions import DataMissingError


class Stock(models.Model):
    name = models.CharField(max_length=10, unique=True, null=False)
    code = models.CharField(max_length=10, null=False)
    market_code = models.PositiveSmallIntegerField()
    isindex = models.BooleanField(default=False)

    class Meta:
        unique_together = ('code', 'market_code')

    def __str__(self):
        return '%s(%s)' % (self.name, self.code)

    def __repr__(self):
        return self.__str__()

    def detail_page_url(self):
        return reverse('stock_analyze:page-stock-detail', args=[self.id])

    def market_name(self):
        market = {1: '上证', 2: '深证'}
        return market[self.market_code] if self.market_code in market.keys() else '未知'

    market_name.admin_order_field = 'market_code'

    @staticmethod
    def get(**kwargs):
        stocks = Stock.objects.filter(**kwargs).prefetch_related('industry_set')
        if (stocks is not None) and len(stocks) > 0:
            return stocks[0]
        else:
            raise Stock.DoesNotExist

    def get_belong_industries(self):
        return self.industry_set.all()

    def cur_price(self, enable_cache=True):
        pc, pc_change, pc_change_pct, time = sdm.cur_price_info(self.code, self.market_code,
                                                                enable_cache=enable_cache)
        return {'pc': pc, 'pc_change': pc_change, 'pc_change_pct': pc_change_pct, 'update_time': time}

    def recent_data(self, days):
        return sdm.get_recent_data(self.code, self.market_code, days)

    def pv_analyzation(self):
        return sda.volume_mean(self.code, self.market_code)

    def corr_with_industry_stocks(self, industry):
        compare_stocks = industry.get_stocks()
        return sda.stocks_corr_analyzation(300, self, *list(compare_stocks))

    def beta(self):
        index = Stock.objects.get(isindex=True, market_code=self.market_code)
        return sda.beta(self.code, index.code, self.market_code)

    def last_deal_data(self, row, page):
        return sdm.last_deal_data(self.code, self.market_code, row, page)


# ~~~~~~~~~~~~~~~~~ Industry ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class Industry(models.Model):
    name = models.CharField(max_length=10, null=False)
    code = models.CharField(max_length=10, unique=True, null=False)
    stocks = models.ManyToManyField(Stock)
    order = models.SmallIntegerField(default=100)

    def __str__(self):
        return '%s' % self.name

    def __repr__(self):
        return self.__str__()

    def detail_page_url(self):
        return reverse('stock_analyze:page-industry-detail', args=[self.id])

    @staticmethod
    def get(**kwargs):
        #  prefetch_related同时查询相关字段放入缓存，减少数据库查询
        industries = Industry.objects.filter(**kwargs).prefetch_related('stocks')
        if (industries is not None) and (len(industries) > 0):
            return industries[0]
        else:
            raise Industry.DoesNotExist

    def get_stocks(self):
        return self.stocks.all()

    def stock_count(self):
        return self.stocks.all().count()

    @staticmethod
    def all_industry_stocks_updown():
        return sdm.industry_stocks_updown_count()

    def cur_industry_stocks_updown(self):
        return Industry.all_industry_stocks_updown()[self.name]

    def industry_stocks_corr(self):
        compare_stocks = self.get_stocks()
        return sda.stocks_corr_analyzation(90, None, *list(compare_stocks))

# ~~~~~~~~~~~~~~~~~ Stock Index ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

stock_analyze/views.py
from a_stock.throttles import DownloadThrottle
from a_stock.utils import print_err
from datetime import datetime

from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q
from django.http import StreamingHttpResponse, Http404
from django.shortcuts import render, get_object_or_404, redirect
from rest_framework import status, generics
from rest_framework.decorators import api_view, renderer_classes, throttle_classes
from rest_framework.exceptions import APIException, ParseError, NotFound, ValidationError
from rest_framework.pagination import PageNumberPagination
from rest_framework.renderers import StaticHTMLRenderer, TemplateHTMLRenderer
from rest_framework.response import Response

import stock_analyze.helper.stock_data_manager as sd
from stock_analyze.exceptions import DataMissingError
from .models import Industry, Stock
from .serializers import StockSerializer4Detail, IndustrySerializer4List, IndustrySerializer4Detail, \
    StockSerializer4List
from stock_analyze.helper.utils import df2html, translate_column_name

QUERY_DATA_MAX_DAYS = 365


# rest_framework pagination class
class LargeResultsSetPagination(PageNumberPagination):
    page_size = 1000
    page_size_query_param = 'page_size'
    max_page_size = 10000


class StandardResultsSetPagination(PageNumberPagination):
    page_size = 100
    page_size_query_param = 'page_size'
    max_page_size = 1000


# ~~~~~~~~~~~~~~~~~~~~~~ page ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
@api_view(('GET',))
@renderer_classes((TemplateHTMLRenderer,))
def page_index(request):
    return Response(template_name='stock_analyze/home.html')


@api_view(('GET',))
@renderer_classes((TemplateHTMLRenderer,))
def page_industries(request):
    return Response(template_name='stock_analyze/industries.html')


@api_view(('GET',))
@renderer_classes((TemplateHTMLRenderer,))
def page_industry_detail(request, id):
    return Response({'id': id}, template_name='stock_analyze/industry_detail.html')


@api_view(('GET',))
@renderer_classes((TemplateHTMLRenderer,))
def page_stock_detail(request, id):
    return Response({'id': id}, template_name='stock_analyze/stock_detail.html')


@api_view(('GET',))
@renderer_classes((TemplateHTMLRenderer,))
def page_index_detail(request, stock_code, market_code):
    index = get_object_or_404(Stock, code=stock_code, market_code=market_code)
    return Response({'id': index.id}, template_name='stock_analyze/index_detail.html')


def page_stock_rzrq(request, id):
    #  融资融券
    stock = get_object_or_404(Stock, id=id)
    if stock.isindex:
        return redirect('http://data.eastmoney.com/rzrq/')
    else:
        return redirect('http://data.eastmoney.com/rzrq/stock/{}.html'.format(stock.code))


# ~~~~~~~~~~~~~~~~~~~~~~~ api ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
class IndustryList(generics.ListAPIView):
    queryset = Industry.objects.order_by('order')
    serializer_class = IndustrySerializer4List
    pagination_class = StandardResultsSetPagination


class IndustryDetail(generics.RetrieveAPIView):
    queryset = Industry.objects.all()
    serializer_class = IndustrySerializer4Detail


class StockDetail(generics.RetrieveAPIView):
    queryset = Stock.objects.all()
    serializer_class = StockSerializer4Detail


@api_view(('GET',))
def stock_cur_price_realtime(request, stock_code, market_code):
    try:
        pc, pc_change, pc_change_pct, time = sd.cur_price_info(
            stock_code, market_code, enable_cache=False)
        return Response(data={
            'pc': pc,
            'pc_change': pc_change,
            'pc_change_pct': pc_change_pct,
            'update_time': time
        })
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
def stock_cur_price(request):
    try:
        pc, pc_change, pc_change_pct, time = sd.cur_price_info(
            request.GET['stock_code'], request.GET['market_code'], enable_cache=False)
        return Response(data={
            'pc': pc,
            'pc_change': pc_change,
            'pc_change_pct': pc_change_pct,
            'update_time': time
        })
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
def all_industry_stocks_updown(request):
    try:
        updowns = Industry.all_industry_stocks_updown()
        return Response(updowns)
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
def industry_stocks_updown(request, industry_id):
    industry = get_object_or_404(Industry, id=industry_id)
    try:
        updowns = industry.cur_industry_stocks_updown()
        return Response(updowns)
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
@renderer_classes((StaticHTMLRenderer,))
def stock_recent_data(request, stock_id, days):
    if days > QUERY_DATA_MAX_DAYS:  # 查询不超过一年
        raise ValidationError

    try:
        stock = Stock.get(id=stock_id)
        df = stock.recent_data(days)
        df.columns = translate_column_name(df.columns)
        table_html = df2html(df)
        return Response(table_html)
    except Stock.DoesNotExist:
        raise NotFound
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
@renderer_classes((StaticHTMLRenderer,))
def stock_pv_analyzation(request, stock_id):
    try:
        stock = Stock.objects.get(id=stock_id)
        df = stock.pv_analyzation()
        table_html = df2html(df)
        return Response(table_html)
    except ObjectDoesNotExist:
        raise NotFound
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
@renderer_classes((StaticHTMLRenderer,))
def stocks_corr_analyzation(request, stock_id):
    try:
        stock = Stock.get(id=stock_id)
        industry = stock.get_belong_industries()[0]
        df_corr = stock.corr_with_industry_stocks(industry)
        table_html = df2html(df_corr)
        return Response(table_html)
    except ObjectDoesNotExist:
        raise NotFound
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
@renderer_classes((StaticHTMLRenderer,))
def industry_stocks_corr_analyzation(request, industry_id):
    try:
        industry = Industry.get(id=industry_id)
        df_corr = industry.industry_stocks_corr()
        table_html = df2html(df_corr)
        return Response(table_html)
    except ObjectDoesNotExist:
        raise NotFound
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
@throttle_classes((DownloadThrottle,))
def download_stock_data(request, stock_id, days):
    # need login
    if not request.user.is_authenticated:
        return redirect('account:page_login')

    # response StreamingHttpResponse to download csv file
    if days > QUERY_DATA_MAX_DAYS:
        raise ValidationError

    try:
        s = Stock.objects.get(id=stock_id)
        date = str(datetime.now().date())
        response = StreamingHttpResponse(
            sd.get_recent_data_generator(s.code, s.market_code, days), content_type="text/csv")
        response['Content-Disposition'] = \
            'attachment; filename="{}-{}-{}.csv"'.format(s.code, date, days)
        return response
    except ObjectDoesNotExist:
        raise NotFound
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
def stocks_search(request):
    try:
        kw = request.GET['kw']
        stocks = Stock.objects.filter(Q(name__contains=kw) | Q(code__contains=kw))[:100]
        serializer = StockSerializer4List(stocks, many=True)
        return Response(serializer.data)
    except KeyError:
        raise ParseError
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
def stock_beta(request, id):
    try:
        stock = Stock.objects.get(id=id)
        beta = stock.beta()
        return Response(dict(result=beta))
    except ObjectDoesNotExist:
        raise Http404
    except DataMissingError:
        return Response(dict(result='数据缺失'))
    except Exception as e:
        print_err(e)
        raise APIException


@api_view(('GET',))
def stock_last_deal_data(request, id):
    try:
        row = request.GET['row']
        page = request.GET['page']
        stock = Stock.objects.get(id=id)
        return Response(stock.last_deal_data(row, page))
    except ObjectDoesNotExist:
        raise ValidationError
    except KeyError:
        raise ValidationError
    except Exception as e:
        print_err(e)
        raise APIException

stock_analyze/templates/stock_analyze/home.html
{% extends 'common/base.html' %}

{% block subtitle %}首页{% endblock %}

{% block content %}

    <div class="container">
        <div class="jumbotron">
            <div class="container">
                <li><a href="{% url 'stock_analyze:page-industries' %}">板块</a></li>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
<script>
    $(function () {
        active_nav_home();
    });
</script>
{% endblock %}

stock_analyze/templates/stock_analyze/index.html
{% extends 'common/base.html' %}

{% block title %}首页{% endblock %}

{% block content %}

    <div class="container">
        <div class="jumbotron">
            <div class="container">
                <li><a href="{% url 'stock_analyze:page-industries' %}">板块</a></li>
            </div>
        </div>
    </div>

{% endblock %}

{% block script %}
<script>
    $(function () {
        active_nav_home();
    });
</script>
{% endblock %}

stock_analyze/templates/stock_analyze/index_detail.html
{% extends 'common/base.html' %}

{% block subtitle %}指数详情{% endblock %}

{% block style %}
    <style>
        main {
            padding-top: 4.1rem;
        }
    </style>
{% endblock %}

{% block content %}

    <div class="container-fluid">
        {# 名称，股票代码，价格，涨跌幅，涨跌百分比#}
        <div class="row bg-dark" style="padding-top: 1rem;">
            <div class="col-2 mx-auto">
                <h4 id="h-stock-name" class="text-white center">--</h4>
                <h6 id="h-stock-code" class="text-white center">--</h6>
            </div>
            <div class="col-1 mx-auto">
                <p class="text-white center">当前价：</p>
                <p id="p-stock-price" class="center">--</p>
            </div>
            <div class="col-1 mx-auto">
                <p class="text-white center">涨跌幅：</p>
                <p id="p-stock-pc-change" class="center">--</p>
            </div>
            <div class="col-1 mx-auto">
                <p class="text-white center">涨跌比：</p>
                <p id="p-stock-pc-change-pct" class="center">--</p>
            </div>
            <div class="col-2 mx-auto">
                <p class="text-white">更新时间：</p>
                <p id="p-pc-update-time" class="text-white center">--</p>
            </div>
        </div>

        {#    最近90天，30天，7天的平均价格，成交量，价量相关性 #}
        <div class="row bg-dark" style="margin-top: 0.2rem;padding-top: 2rem;">
            <div class="col">
                <h6 class="text-white center">近期该指数的平均价格，成交量</h6>
            </div>
        </div>
        <div class="row bg-dark">
            <div id="div-pv-analyzation" class="col-6"></div>
        </div>

                <!-- 下载历史交易数据 -->
        <div class="row bg-dark" style="margin-top: 0.2rem; padding-top: 1.6rem; padding-bottom:1.6rem;">
            <div class="col">
                <h6 class="text-white center">
                    <a class="text-link" target="_blank" href="{% url 'stock_analyze:api-download-stock-data' id 365 %}">
                        {% if user.is_authenticated %}
                            下载历史交易数据 >>
                        {% else %}
                            下载历史交易数据(请先登录) >>
                        {% endif %}
                    </a>
                </h6>
            </div>
        </div>

        <!-- 个股融资融券数据-->
        <div class="row bg-dark" style="margin-top: 0.2rem; padding-top: 1.6rem; padding-bottom:1.6rem;">
            <div class="col">
                <h6 class="text-white center">
                    <a class="text-link" target="_blank" href="{% url 'stock_analyze:page-stock-rzrq' id %}">
                        融资融券数据 >>
                    </a>
                </h6>
            </div>
        </div>

        <!-- 个股融资融券数据-->
        <div class="row bg-dark" style="margin-top: 0.2rem; padding-top: 1.6rem; padding-bottom:1.6rem;">
            <div class="col">
                <h6 class="text-white center">
                    说明：以上数据仅供参考，不构成任何投资建议。据此进行的投资，风险自担。
                </h6>
            </div>
        </div>

    </div>



{% endblock %}

{% block script %}
    <script>
        "use strict";

        let get_stock_info = function () {
            $.ajax({
                url: "{% url 'stock_analyze:api-stock-detail' id %}",
                type: "GET",
                dataType: "json",
            }).done(function (json) {
                {# basic info #}
                let stock = json;
                $('title').html(stock.name);
                $('#h-stock-name').text(stock.name);
                $('#h-stock-code').text(stock.code);
                let industries = stock.industry_set;
                if (industries && industries.length > 0) {
                    let industry = industries[0];
                    $('#a-industry').text(industry.name).attr('href', industry.detail_page_url);
                }

                {# current price info #}
                let cur_price = stock.cur_price;
                let pc_change_pct = cur_price.pc_change_pct + "%";
                let p_pc = $('#p-stock-price').text(cur_price.pc);
                let sign = parseFloat(cur_price.pc_change) > 0 ? '+' : '';
                let p_pc_change = $('#p-stock-pc-change').text( sign+cur_price.pc_change);
                let p_pc_change_pct = $('#p-stock-pc-change-pct').text(sign+pc_change_pct);
                $('#p-pc-update-time').text(cur_price.update_time);

                let c = parseFloat(cur_price.pc_change_pct);
                if (c > 0) {
                    p_pc.addClass('text-danger');
                    p_pc_change.addClass('text-danger');
                    p_pc_change_pct.addClass('text-danger');
                } else if (c < 0) {
                    p_pc.addClass('text-success');
                    p_pc_change.addClass('text-success');
                    p_pc_change_pct.addClass('text-success');
                } else {
                    p_pc.addClass('text-white');
                    p_pc_change.addClass('text-white');
                    p_pc_change_pct.addClass('text-white');
                }


            }).fail(function () {
            }).always(function () {
            });
        };

        let get_pv_analyzation = function () {
            $.ajax({
                url: "{% url 'stock_analyze:stock_pv_analyzation' id %}",
                type: "GET",
                dataType: "html",
            }).done(function (html) {
                let table = $(html)
                    .addClass('table table-striped table-dark ')
                    .css({'text-align': 'right'});
                $('#div-pv-analyzation').append(table);
            }).fail(function () {
                $('#div-pv-analyzation').html('<p class="text-white">数据缺失</p>')
            }).always(function () {
            });
        };

        $(function () {
            active_nav_data();
            get_stock_info();
            get_pv_analyzation();
        });

    </script>
{% endblock %}

stock_analyze/templates/stock_analyze/industries.html
{% extends 'common/base.html' %}



{% block subtitle %}行业数据{% endblock %}

{% block content %}

    <div class="container-fluid">

                {# 指数 #}
        <div class="row bg-dark" style="padding-top: 0.4rem;">
{#            <div class="col-2 mx-auto">#}
{#                <a class="text-white center" href="{% url 'stock_analyze:page-index-detail' '000001' '1' %}">上证指数</a>#}
{#                <p id="p-szzs" class="center">--</p>#}
{#                <p id="pct-szzs" class="center">--</p>#}
{#            </div>#}
{#            <div class="col-2 mx-auto">#}
{#                <a class="text-white center" href="{% url 'stock_analyze:page-index-detail' '399001' '2' %}">深圳成指</a>#}
{#                <p id="p-szcz" class="center">--</p>#}
{#                <p id="pct-szcz" class="center">--</p>#}
{#            </div>#}
            <div class="col-md-2">
                <a class="text-white center" href="#">上证指数</a>
                <p id="p-szzs" class="center">--</p>
                <p id="pct-szzs" class="center">--</p>
            </div>
            <div class="col-md-2">
                <a class="text-white center" href="#">深圳成指</a>
                <p id="p-szcz" class="center">--</p>
                <p id="pct-szcz" class="center">--</p>
            </div>
        </div>

        <div id="div-industry" class="row"  style="padding-top: 1rem;">
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        "use strict";

        let get_pc = function(stock_code, market_code, parse){
            $.ajax({
                url: "{% url 'stock_analyze:api-stock-cur-price' %}"
                    +"?stock_code="+stock_code+"&market_code="+market_code,
                type: "GET",
                dataType: "json",
            }).then(function (p) {
                if(parse){
                    parse(p);
                }
            }).fail(function (xhr, status, errorThrown) {
            }).always(function (xhr, status) {
            });
        };

        let get_index = function(stock_code, market_code, pc_sele, pct_sele){
            get_pc(stock_code, market_code, function(p){
                let text_cls = 'text-white';
                if(p.pc_change_pct>0){
                    text_cls = 'text-danger';
                }else if(p.pc_change_pct < 0){
                    text_cls = 'text-success';
                }
                $(pc_sele)
                    .text(p.pc)
                    .addClass(text_cls);
                $(pct_sele)
                    .text(p.pc_change_pct>0? '+'+p.pc_change_pct : p.pc_change_pct)
                    .addClass(text_cls);
            });
        };

        let get_indexs = function(){
            get_index('000001', '1', '#p-szzs', '#pct-szzs');
            get_index('399001','2','#p-szcz', '#pct-szcz');
        };

        let get_industries = function () {
            $.ajax({
                url: "{% url 'stock_analyze:api-industry-list' %}",
                type: "GET",
                dataType: "json",
            }).then(function (industries) {
                $.ajax({
                    url: "{% url 'stock_analyze:api-all-stocks-updown' %}",
                    type: "GET",
                    dataType: "json",
                }).done(function (updown) {
                    parse_result(industries, updown);
                })
            }).fail(function (xhr, status, errorThrown) {
            }).always(function (xhr, status) {
            });
        };

        let add_table = function (industries, updown) {
            let table = $("<table></table>")
                .addClass('table table-striped table-dark');
            let tr_head = $("<tr></tr>")
                .append("<th scope='col'>行业</th>")
                .append("<th scope='col'>总市值</th>")
                .append("<th scope='col'>上涨家数</th>")
                .append("<th scope='col'>下跌家数</th>")
                .append("<th scope='col'>换手率</th>");
            let thead = $("<thead></thead>").append(tr_head);
            let tbody = $("<tbody></tbody>");
            $.each(industries, function (i, v) {
                try{
                    let u = updown[v.name];
                    let a = $("<a></a>")
                        .addClass("text-link")
                        .attr("href", v.detail_page_url)
                        .text(v.name);
                    let tr = $("<tr></tr>")
                        .append($("<td></td>").append(a))
                        .append($("<td></td>").text(trans_value(u.total_value)))
                        .append($("<td></td>").addClass('text-danger').text(u.up))
                        .append($("<td></td>").addClass('text-success').text(u.down))
                        .append($("<td></td>").text(parseFloat(u.exchange).toFixed(2) + '%'));
                    tbody.append(tr);
                }catch(e){
                    console.log(e);
                }
            });
            table.append(thead);
            table.append(tbody);

            let div_col = $('<div></div>').addClass('col-lg-6');
            div_col.append(table);

            $('#div-industry').append(div_col);
        };

        let parse_result = function (detail, updown) {
            let industries = detail.results;

            if (industries && industries.length > 30) {
                let indus1 =  industries.slice(0, parseInt(industries.length / 2)) ;
                let indus2 =  industries.slice(parseInt(industries.length / 2)) ;
                add_table(indus1, updown);
                add_table(indus2, updown);
            } else {
                add_table(industries || [], updown);
            }
        };


        let trans_value = function (value) {
            let t = parseFloat(value);
            if (value > 1000000000000) {
                t = (value / 1000000000000).toFixed(1) + '万亿';
            } else if (value > 100000000) {
                t = (value / 100000000).toFixed(1) + '亿';
            } else if (value > 10000) {
                t = (value / 10000).toFixed(1) + '万';
            } else {
                t = value;
            }
            return t;
        };

        $(function () {
            active_nav_data();
            get_industries();
            get_indexs();
        });
    </script>
{% endblock %}