account/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

app_name = 'account'

urlpatterns = [
    # ~~~~~~~~~~~~~~~~~~~~~ page html~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('page/login/', views.page_login, name='page_login'),
    path('page/register/', views.page_register, name='page_register'),
    path('page/change_password/', views.page_change_password, name='page_change_password'),
    path('page/activate/<key>/', views.account_activate, name='page_activate'),
    path('page/reset_pw_user_idenfity/', views.page_reset_pw_user_identify, name='page_reset_pw_user_identiry'),
    path('page/page_reset_pw/<key>/', views.page_reset_pw_user, name='page_reset_pw'),

    # ~~~~~~~~~~~~~~~~~~~~~ api json~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('api/login/', views.api_login, name='api_login'),
    path('api/logout/', views.api_logout, name='api_logout'),
    path('api/register/', views.api_register, name='api_register'),
    path('api/change_password/', views.api_change_password, name='api_change_password'),
    path('api/reset_pw_user_identify/', views.api_reset_pw_user_identify, name='api_reset_pw_user_identify'),
    path('api/reset_pw/', views.api_reset_pw, name='api_reset_pw'),

]

nav/urls.py
from django.urls import path
from . import views



app_name = 'nav'

urlpatterns = [
    # ~~~~~~~~~~~~~~~~~ page ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('page/sites/', views.page_site_list, name='page-sites'),

    # ~~~~~~~~~~~~~~~~~ api ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('api/sites/', views.api_site_list, name='api-sites'),
    path('api/add_user_site/', views.api_add_user_site, name='api-add-user-site'),
    path('api/remove_user-site/', views.api_remove_user_site, name='api-remove-user-site'),
]

stock_analyze/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from . import views

app_name = 'stock_analyze'

CACHE_TIME_LONG = 60 * 24
CACHE_TIME_MEDIUM = 60 * 10
CACHE_TIME_SHORT = 60 * 1

urlpatterns = [
    # ~~~~~~~~~~~~~~~~~~~~~ page html~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ex: /stock_analyze/page/index
    path('page/index/', views.page_index,
         name='page-index'),
    path('page/industry_list/', views.page_industries,
         name='page-industries'),
    path('page/industries/<int:id>/', views.page_industry_detail,
         name='page-industry-detail'),
    path('page/stocks/<int:id>/', views.page_stock_detail,
         name='page-stock-detail'),
    path('page/index_detail/<stock_code>/<market_code>/', views.page_index_detail,
         name='page-index-detail'),
    path('page/stocks/rzrq/<int:id>', views.page_stock_rzrq, name='page-stock-rzrq'),

    # ~~~~~~~~~~~~~~~~~~~~~~ api json ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    # ex: /stock_analyze/api/industries
    path('api/industries/', cache_page(CACHE_TIME_LONG)(views.IndustryList.as_view()),
         name='api-industry-list'),
    path('api/industries/<int:pk>/', cache_page(CACHE_TIME_LONG)(views.IndustryDetail.as_view()),
         name='api-industry-detail'),
    path('api/industries/stocks_updown/', cache_page(CACHE_TIME_SHORT)(views.all_industry_stocks_updown),
         name='api-all-stocks-updown'),
    path('api/industries/stocks_updown/<int:industry_id>/', cache_page(CACHE_TIME_SHORT)(views.industry_stocks_updown),
         name='api-stocks-updown'),
    path('api/stocks/<int:pk>/', cache_page(CACHE_TIME_SHORT)(views.StockDetail.as_view()),
         name='api-stock-detail'),
    path('api/stocks/cur_price_realtime/<stock_code>/<market_code>/', views.stock_cur_price_realtime,
         name='api-stock-cur-price-realtime'),
    path('api/stocks/cur_price/', cache_page(CACHE_TIME_SHORT)(views.stock_cur_price),
         name='api-stock-cur-price'),
    path('api/stocks/search/', views.stocks_search, name='api-stocks-search'),
    path('api/stocks/beta/<int:id>', cache_page(CACHE_TIME_LONG)(views.stock_beta), name='api-stocks-beta'),
    path('api/stocks/last_deal_data/<int:id>/', cache_page(CACHE_TIME_SHORT)(views.stock_last_deal_data),
         name='last_deal_data'),

    # ~~~~~~~~~~~~~~~~~~~~~~~~ api html ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('api/industries/stocks_corr_analyzation/<int:industry_id>', cache_page(CACHE_TIME_LONG)(views.industry_stocks_corr_analyzation),
         name='industry_stocks_corr_analyzation'),
    path('api/stocks/recent_data/<int:stock_id>/<int:days>', cache_page(CACHE_TIME_LONG)(views.stock_recent_data),
         name='stock_recent_data'),
    path('api/stocks/stock_pv_analyzation/<int:stock_id>', cache_page(CACHE_TIME_LONG)(views.stock_pv_analyzation),
         name='stock_pv_analyzation'),
    path('api/stocks/stocks_corr_analyzation/<int:stock_id>', cache_page(CACHE_TIME_LONG)(views.stocks_corr_analyzation),
         name='stocks_corr_analyzation'),

    # ~~~~~~~~~~~~~~~~~~~~~~~~~ api file ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    path('api/data_download/stocks/<int:stock_id>/<int:days>', views.download_stock_data,
         name='api-download-stock-data'),

]

templates/common/base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="zh">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="股票，数据，门户">


    <!-- 新 Bootstrap4 核心 CSS 文件 -->
    <link href="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/css/bootstrap.min.css" rel="stylesheet">
    {#    <link rel="stylesheet" type="text/css" href="{% static 'common/css/bootstrap.css' %}">#}

    <!-- jquery-confirm -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/jquery-confirm/3.3.4/jquery-confirm.min.css">

    <!-- taucharts -->
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/taucharts.2.dark.min.css' %}">
{#    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/taucharts@2/dist/taucharts.dark.min.css">#}

    {% compress css %}
    <!-- my style -->
    <link rel="stylesheet" type="text/css" href="{% static 'common/css/style.css' %}">

    {% block style %}
        <style>
            main {
                padding-top: 4rem;
            }
        </style>
    {% endblock %}

    {% endcompress %}

    <link rel="shortcut icon" type="image/png" href="{% static 'common/img/favicon.ico' %}"/>

    <title>{% block title %}扬基数据{% endblock %}-{% block subtitle %}首页{% endblock %}</title>



</head>

{% block body %}
    <body class="bg-secondary">

    {% block sidebar %}
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">

            <h4 class="navbar-brand font-weight-bold" style="text-shadow: black 10px 6px 6px;">
                扬基数据
            </h4>

            <button class="navbar-toggler collapsed" type="button" data-toggle="collapse"
                    data-target="#navbarsExampleDefault"
                    aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="navbar-collapse collapse" id="navbarsExampleDefault">
                <ul class="navbar-nav mr-auto">
                    <!-- <li class="nav-item" id="nav-home">
                        <a class="nav-link" href="#">首页 <span class="sr-only">(current)</span></a>
                    </li> -->
                    <li class="nav-item" id="nav-data">
                        <a class="nav-link" href="{% url 'home' %}">数据</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'nav:page-sites' %}" id="nav-sites">导航</a>
                    </li>
                </ul>

                <form id="form-search" class="form-inline my-2 my-lg-0" method="get"
                      action="{% url 'stock_analyze:api-stocks-search' %}">
                    <input class="form-control mr-sm-2" type="text" placeholder="请输入股票名称或代码" aria-label="Search"
                           name="kw">
                    <button class="btn btn-secondary my-2 my-sm-0" type="submit"><span
                            class="glyphicon glyphicon-search"></span>搜索
                    </button>
                </form>

                <ul class="navbar-nav" style="padding-left: 2rem; ">
                    {% if user.is_authenticated %}
                        <li id="li-account" class="nav-item"><a class="nav-link"
                                                                href="#">{{ user.userprofile.nickname | truncatechars:8 }}</a>
                        </li>
                        <li id="li-logout" class="nav-item"><a class="nav-link" href="#">退出</a></li>
                    {% else %}
                        <li id="li-login" class="nav-item"><a class="nav-link"
                                                              href="{% url 'account:page_login' %}?next={{ request.path }}">登录</a>
                        </li>
                        <li id="li-register" class="nav-item"><a class="nav-link"
                                                                 href="{% url 'account:page_register' %}">注册</a>
                        </li>
                    {% endif %}
                </ul>

            </div>
        </nav>
    {% endblock %}

    <main role="main">
        {% block content %}

        {% endblock %}
    </main>

{% endblock %}

<!-- jQuery文件。务必在bootstrap.min.js 之前引入 -->
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
{#<script src="{% static 'common/js/jquery.js' %}"></script>#}
<!-- 最新的 Bootstrap4 核心 JavaScript 文件 -->
<script src="https://cdn.bootcss.com/twitter-bootstrap/4.2.1/js/bootstrap.min.js"></script>
{#<script src="{% static 'common/js/bootstrap.js' %}"></script>#}
<!-- jquery-confirm -->
<script src="https://cdn.bootcss.com/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>

<!-- taucharts -->
{#<script src="{% static 'common/js/d3.4.13.0.min.js' %}" charset="utf-8"></script>#}
<script src="https://cdn.bootcss.com/d3/4.13.0/d3.min.js"></script>
<script src="{% static 'common/js/taucharts.2.min.js' %}" type="text/javascript"></script>


{% compress js %}
<script src="{% static 'common/js/utils.js' %}"></script>
<script>
    'use strict';

    let active_nav_home = function () {
        $('#nav-home').addClass('active');
    };
    let active_nav_data = function () {
        $('#nav-data').addClass('active');
    };
    let active_nav_news = function () {
        $('#nav-news').addClass('active');
    };
    let active_nav_sites = function () {
        $('#nav-sites').addClass('active');
    };

    let parse_search = function (stocks) {
        let ul = $('<ul></ul>').addClass('list-group');
        $.each(stocks, function (i, v) {
            let a = $('<a></a>')
                .addClass('text-link')
                .attr('href', v.detail_page_url)
                .text(v.code + ' ' + v.name);
            let li = $('<li></li>')
                .addClass('list-group-item bg-dark')
                .append(a);
            ul.append(li);
        });
        let container = $('<div></div>').addClass('container').css('padding-top', '0.4rem');
        let row = $('<div></div>').addClass('row');
        let col = $('<div></div>').addClass('col');
        col.append(ul);
        row.append(col);
        container.append(row);
        $('main').html('').append(container);

    };

    let register_search_action = function () {
        if (!$('#form-search')[0]) {
            return;
        }
        $('#form-search').submit(function (e) {
            e.preventDefault();
            let form = $(this);
            let url = form.attr('action');
            $.ajax({
                url: url,
                type: 'GET',
                data: form.serialize(),
            }).done(function (stocks) {
                parse_search(stocks);

            }).fail(function (xhr, status, errorThrown) {
            }).always(function (xhr, status) {
            });
        });
    };


    let register_logout_action = function () {
        if (!$('#li-logout')[0]) {
            return;
        }
        $('#li-logout').on('click', function (e) {
            e.preventDefault();
            $.ajax({
                url: "{% url 'account:api_logout' %}",
                type: "POST",
            }).done(function (res) {
                if (res.success) {
                    $.dialog('退出登录成功');
                    setTimeout(function () {
                        window.location.reload();
                    }, 1200);
                } else if (res.info) {
                    $.dialog(res.info);
                }
            }).fail(function (xhr, status, errorThrown) {
            }).always(function (xhr, status) {
            });
        });
    };


    $(function () {
        init_ajax_csrf();
        init_ajax_err_handelr();
        register_search_action();
        register_logout_action();
    });
</script>

{% block script %}{% endblock %}

{% endcompress %}

</body>
</html>